version: "3.9"

services:
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped

  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    ports:
      - "8080:8080"
    volumes:
      - ./label-studio-data:/label-studio/data
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
    restart: unless-stopped
